#!/bin/bash

dest=/usr/local/bin

dotmatch='\./(.+)\.(.+)'
dotbase=''

for file in ./*.*
do
    if [[ $file =~ $dotmatch ]]
    then
        dotbase="${BASH_REMATCH[1]}"

        cp `pwd`/$file $dest/$dotbase
	chmod 0755 $dest/$dotbase
    fi
done

